global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'volguard_app'
    static_configs:
      - targets: ['volguard:8000']
    metrics_path: '/api/metrics'
    scrape_interval: 5s
