[tool.ruff]
# Target version
target-version = "py311"
line-length = 120

# Use 'select' to specify what we want, then 'ignore' to kill the noise
select = ["E", "F", "W", "C90", "I"]

ignore = [
    "E701", # Multiple statements on one line (colon)
    "E741", # Ambiguous variable name 'l'
    "F401", # Imported but unused
    "F841", # Local variable assigned but never used
    "E722", # Do not use bare 'except'
    "E402", # Module level import not at top of file
    "F541", # f-string without placeholders
    "E712", # Comparison to False
    "W292", # No newline at end of file
    "F403", # import * used
]

[tool.ruff.lint]
# Newer versions of Ruff use this section
ignore = ["E701", "E741", "F401", "F841", "E722", "E402", "F541", "E712", "F403"]

[tool.mypy]
ignore_missing_imports = true
ignore_errors = true
