[tool.ruff]
# Set the line length to 120 to allow longer lines
line-length = 120

# Force Ruff to ignore the style errors currently blocking your build
ignore = [
    "E701", # Multiple statements on one line (colon)
    "E741", # Ambiguous variable name 'l'
    "F401", # Imported but unused
    "F841", # Local variable assigned but never used
    "E722", # Do not use bare 'except'
    "E402", # Module level import not at top of file
    "F541", # f-string without placeholders
    "E712", # Comparison to False
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.mypy]
# Tell the Type Checker to relax as well
ignore_missing_imports = true
ignore_errors = true
follow_imports = "skip"
